language: csharp
os: linux
dist: trusty
sudo: required
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono: latest
dotnet: 2.1.300
before_install:
  - wget https://github.com/PowerShell/PowerShell/releases/download/v6.0.2/powershell_6.0.2-1.ubuntu.14.04_amd64.deb
  - sudo dpkg -i powershell_6.0.2-1.ubuntu.14.04_amd64.deb
  - sudo apt-get install -f
script: pwsh -File build.ps1 -BuildCore -TestCore -PackCore -BuildSamples
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/af257a163f30e5401654
    on_success: change
    on_failure: always
    on_start: never
