language: csharp
os: linux
dist: trusty
sudo: required
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono: latest
dotnet: 2.0.0
script:
  - dotnet restore src/Dock.Model
  - dotnet build src/Dock.Model/Dock.Model.csproj -c Release -f netstandard2.0
  - dotnet publish src/Dock.Model/Dock.Model.csproj -c Release -f netstandard2.0
  - dotnet restore tests/Dock.Model.UnitTests
  - dotnet test tests/Dock.Model.UnitTests/Dock.Model.UnitTests.csproj -c Release -f netcoreapp2.0
  - dotnet restore src/Dock.Avalonia
  - dotnet build src/Dock.Avalonia/Dock.Avalonia.csproj -c Release -f netstandard2.0
  - dotnet publish src/Dock.Avalonia/Dock.Avalonia.csproj -c Release -f netstandard2.0
  - dotnet restore tests/Dock.Avalonia.UnitTests
  - dotnet test tests/Dock.Avalonia.UnitTests/Dock.Avalonia.UnitTests.csproj -c Release -f netcoreapp2.0
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/af257a163f30e5401654
    on_success: change
    on_failure: always
    on_start: never
