language: csharp
os: linux
dist: trusty
sudo: required
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono: latest
dotnet: 2.1.300
script: ./build.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/af257a163f30e5401654
    on_success: change
    on_failure: always
    on_start: never
