name: $(date:yyyyMMdd)$(rev:-rr)

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'
  NetCoreSDK: '5.0.400'
  PublishFramework: 'net5.0'
  PublishProject: ''
  PublishRuntime: ''

jobs:
  - template: build/templates/Test-PowerShell.yml
    parameters:
      name: 'Test Windows'
      vmImage: 'windows-2022'
      BuildConfiguration:  $(BuildConfiguration)

  - template: build/templates/Test-Bash.yml
    parameters:
      name: 'Test Linux'
      vmImage: 'ubuntu-20.04'
      BuildConfiguration:  $(BuildConfiguration)

  - template: build/templates/Test-Bash.yml
    parameters:
      name: 'Test macOS'
      vmImage: 'macOS-11'
      BuildConfiguration:  $(BuildConfiguration)

  - template: build/templates/Pack-MyGet.yml
    parameters:
      name: 'Pack MyGet'
      vmImage: 'windows-2022'
      BuildConfiguration:  $(BuildConfiguration)

  - template: build/templates/Pack-NuGet.yml
    parameters:
      name: 'Pack NuGet'
      vmImage: 'windows-2022'
      BuildConfiguration:  $(BuildConfiguration)

  - template: build/templates/Publish-PowerShell.yml
    parameters:
      name: 'Publish Windows'
      vmImage: 'windows-2022'
      PublishProject: 'AvaloniaDemo'
      PublishRuntime: 'win7-x64'

  - template: build/templates/Publish-PowerShell.yml
    parameters:
      name: 'Publish Windows net461'
      vmImage: 'windows-2022'
      PublishFramework: 'net461'
      PublishProject: 'AvaloniaDemo'
      PublishRuntime: 'win7-x64'

  - template: build/templates/Publish-Bash.yml
    parameters:
      name: 'Publish Ubuntu'
      vmImage: 'ubuntu-20.04'
      PublishProject: 'AvaloniaDemo'
      PublishRuntime: 'ubuntu.14.04-x64'

  - template: build/templates/Publish-Bash.yml
    parameters:
      name: 'Publish Debian'
      vmImage: 'ubuntu-20.04'
      PublishProject: 'AvaloniaDemo'
      PublishRuntime: 'debian.8-x64'

  - template: build/templates/Publish-Bash.yml
    parameters:
      name: 'Publish macOS'
      vmImage: 'macOS-11'
      PublishProject: 'AvaloniaDemo'
      PublishRuntime: 'osx.10.12-x64'
