name: $(date:yyyyMMdd)$(rev:-rr)

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'
  NetCoreSDK: '5.0.400'
  PublishFramework: 'net5.0'
  PublishProject: 'AvaloniaDemo'
  PublishRuntime: ''

jobs:
  - template: build/templates/Test-PowerShell.yml
    parameters:
      name: 'Test_Windows'
      vmImage: 'windows-2022'
      BuildConfiguration: ${{ variables.BuildConfiguration }}

  - template: build/templates/Test-Bash.yml
    parameters:
      name: 'Test_Linux'
      vmImage: 'ubuntu-20.04'
      BuildConfiguration: ${{ variables.BuildConfiguration }}

  - template: build/templates/Test-Bash.yml
    parameters:
      name: 'Test_macOS'
      vmImage: 'macOS-11'
      BuildConfiguration: ${{ variables.BuildConfiguration }}

  - template: build/templates/Pack-MyGet.yml
    parameters:
      name: 'Pack_MyGet'
      vmImage: 'windows-2022'
      BuildConfiguration: ${{ variables.BuildConfiguration }}

  - template: build/templates/Pack-NuGet.yml
    parameters:
      name: 'Pack_NuGet'
      vmImage: 'windows-2022'
      BuildConfiguration: ${{ variables.BuildConfiguration }}

  - template: build/templates/Publish-PowerShell.yml
    parameters:
      name: 'Publish_Windows'
      vmImage: 'windows-2022'
      BuildConfiguration: ${{ variables.BuildConfiguration }}
      PublishFramework: ${{ variables.PublishFramework }}
      PublishProject: ${{ variables.PublishProject }}
      PublishRuntime: 'win7-x64'

  - template: build/templates/Publish-Bash.yml
    parameters:
      name: 'Publish_Ubuntu'
      vmImage: 'ubuntu-20.04'
      BuildConfiguration: ${{ variables.BuildConfiguration }}
      PublishFramework: ${{ variables.PublishFramework }}
      PublishProject: ${{ variables.PublishProject }}
      PublishRuntime: 'ubuntu.14.04-x64'

  - template: build/templates/Publish-Bash.yml
    parameters:
      name: 'Publish_Debian'
      vmImage: 'ubuntu-20.04'
      BuildConfiguration: ${{ variables.BuildConfiguration }}
      PublishFramework: ${{ variables.PublishFramework }}
      PublishProject: ${{ variables.PublishProject }}
      PublishRuntime: 'debian.8-x64'

  - template: build/templates/Publish-Bash.yml
    parameters:
      name: 'Publish_macOS'
      vmImage: 'macOS-11'
      BuildConfiguration: ${{ variables.BuildConfiguration }}
      PublishFramework: ${{ variables.PublishFramework }}
      PublishProject: ${{ variables.PublishProject }}
      PublishRuntime: 'osx.10.12-x64'
