version: 2
jobs:
  build:
    working_directory: ~/Dock
    docker:
      - image: microsoft/dotnet:2.1.300-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet --info
      - run: ./build.sh
