version: 2
jobs:
  build:
    working_directory: ~/Dock
    docker:
      - image: microsoft/dotnet:2.1.300-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install curl gnupg apt-transport-https
      - run: curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      - run: sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/microsoft.list'
      - run: sudo apt-get update
      - run: sudo apt-get install -y powershell
      - run: pwsh -File build.ps1 -BuildCore -TestCore -PackCore -BuildSamples
