name: CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macOS-10.14]
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-preview7-012821
    - name: Build Release
      run: dotnet build -c Release
    - name: Test Release
      run: dotnet test -c Release
    - name: Pack Release
      if: github.event_name != 'pull_request'
      run: dotnet pack -c Release -o ./artifacts/NuGet
    - name: Publish Windows
      if: matrix.os == 'windows-2019'
      run: |
        dotnet publish -c Release -f net461 -r win7-x64 -o ./artifacts/AvaloniaDemo-net461-win7-x64 ./samples/AvaloniaDemo/AvaloniaDemo.csproj
        dotnet publish -c Release -f netcoreapp2.2 -r win7-x64 -o ./artifacts/AvaloniaDemo-netcoreapp2.2-win7-x64 ./samples/AvaloniaDemo/AvaloniaDemo.csproj
        dotnet publish -c Release -f netcoreapp3.0 -r win7-x64 -o ./artifacts/AvaloniaDemo-netcoreapp3.0-win7-x64 ./samples/AvaloniaDemo/AvaloniaDemo.csproj
    - name: Publish Linux
      if: matrix.os == 'ubuntu-18.04'
      run: |
        dotnet publish -c Release -f netcoreapp3.0 -r debian.8-x64 -o ./artifacts/AvaloniaDemo-netcoreapp3.0-debian.8-x64 ./samples/AvaloniaDemo/AvaloniaDemo.csproj
        dotnet publish -c Release -f netcoreapp3.0 -r ubuntu.14.04-x64 -o ./artifacts/AvaloniaDemo-netcoreapp3.0-ubuntu.14.04-x64 ./samples/AvaloniaDemo/AvaloniaDemo.csproj
    - name: Archive Linux
      if: matrix.os == 'ubuntu-18.04'
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -r ./artifacts/Zip/AvaloniaDemo-netcoreapp3.0-ubuntu.14.04-x64.zip ./artifacts/AvaloniaDemo-netcoreapp3.0-ubuntu.14.04-x64
    - name: Upload Linux
      if: matrix.os == 'ubuntu-18.04'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo-netcoreapp3.0-ubuntu.14.04-x64
        path: ./artifacts/Zip/AvaloniaDemo-netcoreapp3.0-ubuntu.14.04-x64.zip
    - name: Publish macOS
      if: matrix.os == 'macOS-10.14'
      run: dotnet publish -c Release -f netcoreapp3.0 -r osx.10.12-x64 -o ./artifacts/AvaloniaDemo-netcoreapp3.0-osx.10.12-x64 ./samples/AvaloniaDemo/AvaloniaDemo.csproj
    - name: Archive macOS
      if: matrix.os == 'macOS-10.14'
      run: zip -r ./artifacts/Zip/AvaloniaDemo-netcoreapp3.0-osx.10.12-x64.zip ./artifacts/AvaloniaDemo-netcoreapp3.0-osx.10.12-x64
    - name: Upload macOS
      if: matrix.os == 'macOS-10.14'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo-netcoreapp3.0-osx.10.12-x64
        path: ./artifacts/Zip/AvaloniaDemo-netcoreapp3.0-osx.10.12-x64.zip
