name: .NET Core CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        version: 3.0.100-preview7-012821
    - name: Build with dotnet
      run: dotnet build --configuration Release
